// klc_frontend::lexer — KL source code tokenizer
//
// Transforms KL source text into a sequence of tokens.
// Handles indentation-based block detection (INDENT/DEDENT tokens).
// Reference: docs/02-formal-grammar.md

use klc_core::span::Span;
use crate::token::{Token, TokenKind};

/// The KL lexer.
pub struct Lexer {
    source: String,
    chars: Vec<char>,
    pos: usize,
    line: usize,
    column: usize,
    indent_stack: Vec<usize>,
    pending_tokens: Vec<Token>,
    at_bol: bool,
}

impl Lexer {
    /// Create a new lexer for the given source text.
    pub fn new(source: &str) -> Self {
        let chars: Vec<char> = source.chars().collect();
        Self {
            source: source.to_string(),
            chars,
            pos: 0,
            line: 1,
            column: 1,
            indent_stack: vec![0],
            pending_tokens: Vec::new(),
            at_bol: true,
        }
    }

    /// Tokenize the entire source and return all tokens with INDENT/DEDENT.
    pub fn tokenize(&mut self) -> Vec<Token> {
        let mut tokens = Vec::new();
        loop {
            match self.next_token() {
                Some(tok) => {
                    let is_eof = matches!(tok.kind, TokenKind::Eof);
                    tokens.push(tok);
                    if is_eof {
                        break;
                    }
                }
                None => break,
            }
        }
        tokens
    }

    /// Advance to the next token.
    fn next_token(&mut self) -> Option<Token> {
        // Drain any pending tokens (generated by indentation handling).
        if !self.pending_tokens.is_empty() {
            return Some(self.pending_tokens.remove(0));
        }

        self.skip_whitespace_and_comments();

        if self.pos >= self.chars.len() {
            // Emit DEDENTs for remaining indentation levels.
            let remaining = self.indent_stack.len() - 1;
            if remaining > 0 {
                self.indent_stack.truncate(1);
                return Some(self.make_token(TokenKind::Dedent));
            }
            return Some(self.make_token(TokenKind::Eof));
        }

        let c = self.chars[self.pos];
        // Detect newline.
        if c == '\n' {
            self.advance();
            self.handle_newline();
            return Some(self.make_token(TokenKind::Newline));
        }

        self.at_bol = false;

        // Single-character tokens.
        if let Some(kind) = match c {
            '+' => { self.advance(); Some(TokenKind::Plus) }
            '-' => {
                self.advance();
                if self.current() == '>' { self.advance(); Some(TokenKind::Arrow) }
                else { Some(TokenKind::Minus) }
            }
            '*' => { self.advance(); Some(TokenKind::Star) }
            '/' => { self.advance(); Some(TokenKind::Slash) }
            '%' => { self.advance(); Some(TokenKind::Percent) }
            '=' => {
                self.advance();
                if self.current() == '=' { self.advance(); Some(TokenKind::EqualsEquals) }
                else if self.current() == '>' { self.advance(); Some(TokenKind::FatArrow) }
                else { Some(TokenKind::Equals) }
            }
            '!' => {
                self.advance();
                if self.current() == '=' { self.advance(); Some(TokenKind::BangEquals) }
                else { Some(TokenKind::Bang) }
            }
            '<' => {
                self.advance();
                if self.current() == '<' {
                    self.advance();
                    if self.current() == '=' { self.advance(); Some(TokenKind::LessLessEquals) }
                    else { Some(TokenKind::LessLess) }
                } else if self.current() == '=' { self.advance(); Some(TokenKind::LessEquals) }
                else { Some(TokenKind::Less) }
            }
            '>' => {
                self.advance();
                if self.current() == '>' {
                    self.advance();
                    if self.current() == '=' { self.advance(); Some(TokenKind::GreaterGreaterEquals) }
                    else { Some(TokenKind::GreaterGreater) }
                } else if self.current() == '=' { self.advance(); Some(TokenKind::GreaterEquals) }
                else { Some(TokenKind::Greater) }
            }
            '&' => {
                self.advance();
                if self.current() == '&' { self.advance(); Some(TokenKind::And) }
                else if self.current() == '=' { self.advance(); Some(TokenKind::AmpersandEquals) }
                else { Some(TokenKind::Ampersand) }
            }
            '|' => {
                self.advance();
                if self.current() == '|' { self.advance(); Some(TokenKind::Or) }
                else if self.current() == '=' { self.advance(); Some(TokenKind::PipeEquals) }
                else { Some(TokenKind::Pipe) }
            }
            '^' => {
                self.advance();
                if self.current() == '=' { self.advance(); Some(TokenKind::CaretEquals) }
                else { Some(TokenKind::Caret) }
            }
            '~' => { self.advance(); Some(TokenKind::Tilde) }
            '.' => { self.advance(); Some(TokenKind::Dot) }
            ',' => { self.advance(); Some(TokenKind::Comma) }
            ':' => { self.advance(); Some(TokenKind::Colon) }
            '?' => {
                self.advance();
                if self.current() == '.' { self.advance(); Some(TokenKind::QuestionDot) }
                else { Some(TokenKind::Question) }
            }
            '(' => { self.advance(); Some(TokenKind::LParen) }
            ')' => { self.advance(); Some(TokenKind::RParen) }
            '[' => { self.advance(); Some(TokenKind::LBracket) }
            ']' => { self.advance(); Some(TokenKind::RBracket) }
            '{' => { self.advance(); Some(TokenKind::LBrace) }
            '}' => { self.advance(); Some(TokenKind::RBrace) }
            _ => None,
        } {
            return Some(self.make_token(kind));
        }

        // Identifiers, keywords, types.
        if c.is_alphabetic() || c == '_' {
            let start = self.pos;
            while self.pos < self.chars.len()
                && (self.chars[self.pos].is_alphanumeric() || self.chars[self.pos] == '_')
            {
                self.advance();
            }
            let word: String = self.chars[start..self.pos].iter().collect();
            let kind = self.keyword_or_identifier(&word);
            return Some(self.make_token(kind));
        }

        // Numbers.
        if c.is_ascii_digit() {
            return Some(self.lex_number());
        }

        // Strings.
        if c == '"' {
            return Some(self.lex_string());
        }

        // Chars.
        if c == '\'' {
            return Some(self.lex_char());
        }

        // Unknown character.
        let ch = c;
        self.advance();
        Some(self.make_token(TokenKind::LexError(format!("unexpected character: '{}'", ch))))
    }

    /// Determine if a word is a keyword, type name, or plain identifier.
    fn keyword_or_identifier(&self, word: &str) -> TokenKind {
        match word {
            "fn" => TokenKind::Fn,
            "class" => TokenKind::Class,
            "abs" => TokenKind::Abs,
            "struct" => TokenKind::Struct,
            "enum" => TokenKind::Enum,
            "contract" => TokenKind::Contract,
            "if" => TokenKind::If,
            "elif" => TokenKind::Elif,
            "else" => TokenKind::Else,
            "while" => TokenKind::While,
            "for" => TokenKind::For,
            "in" => TokenKind::In,
            "match" => TokenKind::Match,
            "return" => TokenKind::Return,
            "break" => TokenKind::Break,
            "defer" => TokenKind::Defer,
            "guard" => TokenKind::Guard,
            "unsafe" => TokenKind::Unsafe,
            "async" => TokenKind::Async,
            "await" => TokenKind::Await,
            "const" => TokenKind::Const,
            "loop" => TokenKind::Loop,
            "type" => TokenKind::Type,
            "true" => TokenKind::True,
            "false" => TokenKind::False,
            "None" => TokenKind::None,
            "ok" => TokenKind::OkKw,
            "error" => TokenKind::ErrKw,
            "extern" => TokenKind::Extern,
            _ => TokenKind::Identifier(word.to_string()),
        }
    }

    fn lex_number(&mut self) -> Token {
        let start = self.pos;
        let mut is_float = false;

        // Handle hex: 0x...
        if self.chars[start] == '0' && self.peek() == 'x' {
            self.advance();
            self.advance();
            while self.pos < self.chars.len()
                && self.chars[self.pos].is_ascii_hexdigit()
            {
                self.advance();
            }
            let value: String = self.chars[start..self.pos].iter().collect();
            return self.make_token(TokenKind::Integer(value));
        }

        // Handle binary: 0b...
        if self.chars[start] == '0' && self.peek() == 'b' {
            self.advance();
            self.advance();
            while self.pos < self.chars.len()
                && (self.chars[self.pos] == '0' || self.chars[self.pos] == '1')
            {
                self.advance();
            }
            let value: String = self.chars[start..self.pos].iter().collect();
            return self.make_token(TokenKind::Integer(value));
        }

        // Decimal digits.
        while self.pos < self.chars.len() && self.chars[self.pos].is_ascii_digit() {
            self.advance();
        }

        // Float: dot followed by digit.
        if self.peek() == '.' {
            let next = self.chars.get(self.pos + 1).copied();
            if next.is_some_and(|c| c.is_ascii_digit()) {
                is_float = true;
                self.advance(); // consume '.'
                while self.pos < self.chars.len() && self.chars[self.pos].is_ascii_digit() {
                    self.advance();
                }
            }
        }

        let value: String = self.chars[start..self.pos].iter().collect();
        if is_float {
            self.make_token(TokenKind::Float(value))
        } else {
            self.make_token(TokenKind::Integer(value))
        }
    }

    fn lex_string(&mut self) -> Token {
        self.advance(); // consume opening "
        let start = self.pos;
        while self.pos < self.chars.len() && self.chars[self.pos] != '"' {
            if self.chars[self.pos] == '\\' {
                self.advance(); // skip escape
            }
            self.advance();
        }
        let value: String = self.chars[start..self.pos].iter().collect();
        self.advance(); // consume closing "
        self.make_token(TokenKind::String(value))
    }

    fn lex_char(&mut self) -> Token {
        self.advance(); // consume opening '
        let value = if self.chars[self.pos] == '\\' {
            self.advance();
            let ch = self.chars[self.pos];
            self.advance();
            match ch {
                'n' => '\n',
                't' => '\t',
                '\\' => '\\',
                '\'' => '\'',
                _ => ch,
            }
        } else {
            let ch = self.chars[self.pos];
            self.advance();
            ch
        };
        if self.pos < self.chars.len() && self.chars[self.pos] == '\'' {
            self.advance(); // consume closing '
        }
        self.make_token(TokenKind::Char(value.to_string()))
    }

    // -----------------------------------------------------------------------
    // Indentation handling
    // -----------------------------------------------------------------------

    fn handle_newline(&mut self) {
        self.at_bol = true;
        let indent = self.measure_indent();
        let last = *self.indent_stack.last().unwrap_or(&0);

        if indent > last {
            self.indent_stack.push(indent);
            self.pending_tokens.push(self.make_token(TokenKind::Indent));
        } else if indent < last {
            while let Some(&level) = self.indent_stack.last() {
                if level <= indent {
                    break;
                }
                self.indent_stack.pop();
                self.pending_tokens.push(self.make_token(TokenKind::Dedent));
            }
        }
    }

    fn measure_indent(&mut self) -> usize {
        let mut count = 0;
        let mut i = self.pos;
        while i < self.chars.len() {
            match self.chars[i] {
                ' ' => {
                    count += 1;
                    i += 1;
                }
                '\t' => {
                    count += 4;
                    i += 1;
                }
                '\n' | '\r' => {
                    // Blank line — reset and keep reading.
                    count = 0;
                    i += 1;
                }
                '#' => {
                    // Comment — skip to end of line.
                    while i < self.chars.len() && self.chars[i] != '\n' {
                        i += 1;
                    }
                    count = 0;
                    i += 1;
                }
                _ => break,
            }
        }
        // Do NOT advance the main position — measure_indent is a lookahead.
        // The main lexer position is advanced by skip_whitespace_and_comments.
        count
    }

    // -----------------------------------------------------------------------
    // Utility helpers
    // -----------------------------------------------------------------------

    fn skip_whitespace_and_comments(&mut self) {
        while self.pos < self.chars.len() {
            match self.chars[self.pos] {
                ' ' | '\t' | '\r' => {
                    self.advance();
                }
                '#' => {
                    // Line comment: skip to newline.
                    while self.pos < self.chars.len() && self.chars[self.pos] != '\n' {
                        self.advance();
                    }
                }
                _ => break,
            }
        }
    }

    fn advance(&mut self) {
        if self.pos < self.chars.len() {
            if self.chars[self.pos] == '\n' {
                self.line += 1;
                self.column = 1;
            } else {
                self.column += 1;
            }
            self.pos += 1;
        }
    }

    fn peek(&self) -> char {
        self.chars.get(self.pos + 1).copied().unwrap_or('\0')
    }

    /// Return the character at the current position, or NUL if at end.
    fn current(&self) -> char {
        self.chars.get(self.pos).copied().unwrap_or('\0')
    }

    fn make_token(&self, kind: TokenKind) -> Token {
        Token::new(kind, Span::dummy())
    }
}
