use crate::ir::*;
use super::{GeneratedFile, BackendOutput, UiBackend};
use std::sync::atomic::{AtomicUsize, Ordering};

static EL_COUNTER: AtomicUsize = AtomicUsize::new(0);

fn fresh_el() -> String {
    let id = EL_COUNTER.fetch_add(1, Ordering::Relaxed);
    format!("_el{}", id)
}

pub struct WebBackend;

impl WebBackend {
    pub fn new() -> Self { Self }
}

impl UiBackend for WebBackend {
    fn name(&self) -> &str {
        "web"
    }

    fn target_triple(&self) -> &str {
        "wasm32-unknown-unknown"
    }

    fn generate(&self, program: &UiProgram) -> BackendOutput {
        let mut js = String::new();

        // Import ESM runtimes
        js.push_str("// Generated by Kyle UI Compiler\n");
        js.push_str("// Target: Web (JS/DOM) — ES Modules\n\n");

        // Include reactivity and router runtimes as ESM imports
        js.push_str("import { ReactiveState, Binding, createKyleEvent } from './reactivity.js';\n");
        js.push_str("import { Router, routeParams } from './router.js';\n");
        js.push_str("import { A11yManager } from './a11y.js';\n");
        js.push_str("import { portalManager } from './portal.js';\n");
        js.push_str("import { ErrorBoundary } from './error_boundary.js';\n");
        js.push_str("import { getI18n, t, setLocale } from './i18n.js';\n");
        js.push_str("const _i18n = getI18n();\n");
        js.push_str("const _a11y = new A11yManager();\n\n");

        // Generate styles
        let style_js = generate_styles(&program.styles);
        js.push_str(&style_js);

        // Generate animations
        let anim_js = generate_animations(&program.animations);
        js.push_str(&anim_js);

        // Determine component name from view path — always export as 'render'
        let comp_name = "render".to_string();

        // Generate component function (exported at end)
        js.push_str("function render(container, initialState = {}) {\n");
        js.push_str("  const state = new ReactiveState(initialState);\n");

        // Translate code blocks (@(...)) to JS
        for block in &program.code_blocks {
            let js_block = translate_kyle_block_to_js(block);
            if !js_block.is_empty() {
                js.push_str("  // From Kyle block:\n");
                for line in js_block.lines() {
                    js.push_str(&format!("  {}\n", line));
                }
            }
        }

        js.push_str("  const el = document.createDocumentFragment();\n");

        for node in &program.body {
            gen_node(node, &mut js, 2, "el");
        }

        js.push_str("  return { element: el, state };\n");
        js.push_str("}\n\n");

        // Route registration
        if !program.view_paths.is_empty() {
            js.push_str("// Auto-register routes\n");
            js.push_str("if (typeof window !== 'undefined') {\n");
            js.push_str("  if (!window.__KYLE_ROUTES) window.__KYLE_ROUTES = {};\n");
            for path in &program.view_paths {
                js.push_str(&format!("  window.__KYLE_ROUTES[{:?}] = render;\n", path));
            }
            js.push_str("}\n\n");
        }

        // Export render function
        js.push_str("export { render };\n");

        // Build HTML shell
        let html = generate_html();

        BackendOutput {
            files: vec![GeneratedFile {
                path: format!("ui-runtime.js"),
                content: js,
            }],
            html_shell: Some(html),
        }
    }
}

fn gen_node(node: &UiNode, js: &mut String, indent: usize, parent: &str) {
    let el = fresh_el();
    let ind = " ".repeat(indent);
    let ind2 = " ".repeat(indent + 2);

    match node {
        UiNode::Element { tag, attrs, children } => {
            let tag_js = js_tag(tag);
            if tag == &ComponentTag::Portal {
                let mut target = "body";
                for a in attrs {
                    if a.name == "target" {
                        if let AttrValue::String(ref v) = a.value { target = v; }
                    }
                }
                js.push_str(&format!("{}// Portal: render to '{}'\n", ind, target));
                for child in children {
                    gen_node(child, js, indent, &format!("{}_content", el));
                }
                js.push_str(&format!("{}if (typeof {}_content !== 'undefined') {{\n", ind, el));
                js.push_str(&format!("{}  portalManager.create({}_content, {:?});\n", ind, el, target));
                js.push_str(&format!("{}}}\n", ind));
                return;
            }
            if tag == &ComponentTag::ErrorBoundary {
                let b = fresh_el();
                js.push_str(&format!("{}// Error boundary\n", ind));
                js.push_str(&format!("{}const {} = new ErrorBoundary();\n", ind, b));
                js.push_str(&format!("{}const {}_wrap = {}.wrap(() => {{\n", ind, b, b));
                js.push_str(&format!("{}  const {}_c = document.createDocumentFragment();\n", ind, b));
                for child in children {
                    gen_node(child, js, indent + 2, &format!("{}_c", b));
                }
                js.push_str(&format!("{}  return {}_c;\n", ind, b));
                js.push_str(&format!("{}}});\n", ind));
                js.push_str(&format!("{}const {}_r = {}_wrap();\n", ind, b, b));
                js.push_str(&format!("{}if ({}_r) {{ {}.appendChild({}_r); }}\n", ind, b, parent, b));
                return;
            }
            if tag == &ComponentTag::Outlet {
                let mut name = "default";
                for a in attrs {
                    if a.name == "name" {
                        if let AttrValue::String(ref v) = a.value { name = v; }
                    }
                }
                js.push_str(&format!("{}// Outlet: '{}'\n", ind, name));
                js.push_str(&format!("{}portalManager.registerOutlet({:?}, {});\n", ind, name, el));
            }
            js.push_str(&format!("{}const {} = document.createElement('{}');\n", ind, el, tag_js));
            gen_attrs(attrs, js, indent, &el);
            gen_events(attrs, js, indent, &el);
            js.push_str(&format!("{}A11yManager.applyAria({}, {:?});\n", ind, el, tag.as_str()));
            for child in children {
                gen_node(child, js, indent + 2, &el);
            }
            js.push_str(&format!("{}{}.appendChild({});\n", ind, parent, el));
        }
        UiNode::SelfClosing { tag, attrs } => {
            let tag_js = js_tag(tag);
            js.push_str(&format!("{}const {} = document.createElement('{}');\n", ind, el, tag_js));
            gen_attrs(attrs, js, indent, &el);
            gen_events(attrs, js, indent, &el);
            js.push_str(&format!("{}A11yManager.applyAria({}, {:?});\n", ind, el, tag.as_str()));
            js.push_str(&format!("{}{}.appendChild({});\n", ind, parent, el));
        }
        UiNode::Slot { name, fallback } => {
            js.push_str(&format!("{}// Slot: {}\n", ind, name));
            if !fallback.is_empty() {
                for child in fallback {
                    gen_node(child, js, indent, parent);
                }
            }
        }
        UiNode::If { condition, then_branch, else_branch } => {
            js.push_str(&format!("{}if ({}) {{\n", ind, condition));
            for child in then_branch {
                gen_node(child, js, indent + 4, parent);
            }
            if !else_branch.is_empty() {
                js.push_str(&format!("{}}} else {{\n", ind));
                for child in else_branch {
                    gen_node(child, js, indent + 4, parent);
                }
            }
            js.push_str(&format!("{}}}\n", ind));
        }
        UiNode::For { item, list, body } => {
            js.push_str(&format!("{}for (const {} of {}) {{\n", ind, item, list));
            for child in body {
                gen_node(child, js, indent + 4, parent);
            }
            js.push_str(&format!("{}}}\n", ind));
        }
        UiNode::Match { expr, cases } => {
            js.push_str(&format!("{}switch ({}) {{\n", ind, expr));
            for case in cases {
                js.push_str(&format!("{}  case {}:\n", ind, case.pattern));
                for child in &case.body {
                    gen_node(child, js, indent + 8, parent);
                }
                js.push_str(&format!("{}    break;\n", ind));
            }
            js.push_str(&format!("{}}}\n", ind));
        }
        UiNode::Expr(e) => {
            js.push_str(&format!("{}// Expression: {}\n", ind, e));
            js.push_str(&format!("{}{}\n", ind, e));
        }
        UiNode::CodeBlock(code) => {
            let js_block = translate_kyle_block_to_js(code);
            if !js_block.is_empty() {
                js.push_str(&format!("{}// From inline Kyle block:\n", ind));
                for line in js_block.lines() {
                    js.push_str(&format!("{}{}\n", ind, line));
                }
            }
        }
        UiNode::Text(text) => {
            js.push_str(&format!("{}{}.appendChild(document.createTextNode({:?}));\n", ind, parent, text));
        }
    }
}

fn gen_attrs(attrs: &[UiAttr], js: &mut String, indent: usize, el: &str) {
    let ind = " ".repeat(indent + 2);
    for attr in attrs {
        // Check if this is a style-related attribute
        if let Some(css_prop) = style_attr_to_css(&attr.name) {
            match &attr.value {
                AttrValue::String(val) => {
                    let css_val = attr_style_value(&attr.name, val);
                    js.push_str(&format!("{}{}.style[{}] = {};\n", ind, el, css_prop, css_val));
                }
                AttrValue::Expr(expr) => {
                    let css_val = if is_simple_key(expr) {
                        format!("state.get({:?})", expr)
                    } else {
                        format!("{}", expr)
                    };
                    js.push_str(&format!("{}const __upd = () => {{ {}.style[{}] = {}; }};\n", ind, el, css_prop, css_val));
                    js.push_str(&format!("{}__upd();\n", ind));
                    // Watch count as a heuristic
                    js.push_str(&format!("{}state.watch('count', __upd);\n", ind));
                }
                AttrValue::Flag => {
                    js.push_str(&format!("{}{}.style[{}] = '1';\n", ind, el, css_prop));
                }
            }
            continue;
        }
        // Check for layout attribute (flexbox)
        if attr.name == "layout" {
            if let AttrValue::String(val) = &attr.value {
                let (ai, jc) = layout_to_flex(val);
                js.push_str(&format!("{}{}.style.display = 'flex';\n", ind, el));
                if !ai.is_empty() {
                    js.push_str(&format!("{}{}.style.alignItems = '{}';\n", ind, el, ai));
                }
                if !jc.is_empty() {
                    js.push_str(&format!("{}{}.style.justifyContent = '{}';\n", ind, el, jc));
                }
            }
            continue;
        }
        // Check for spacing attribute (gap in flexbox)
        if attr.name == "spacing" {
            if let AttrValue::String(val) = &attr.value {
                let v = if val.chars().all(|c| c.is_ascii_digit()) {
                    format!("{}px", val)
                } else { val.clone() };
                js.push_str(&format!("{}{}.style.gap = '{}';\n", ind, el, v));
            }
            continue;
        }
        // Regular attribute handling
        match &attr.value {
            AttrValue::String(val) => {
                match attr.name.as_str() {
                    "tpl" | "style" => {
                        js.push_str(&format!("{}applyStyle({}, {:?});\n", ind, el, val));
                    }
                    "animation" => {
                        js.push_str(&format!("{}applyAnimation({}, {:?});\n", ind, el, val));
                    }
                    "text" | "value" | "label" => {
                        js.push_str(&format!("{}{}.textContent = {:?};\n", ind, el, val));
                    }
                    "class" | "id" | "type" | "placeholder" | "src" | "alt" | "href" => {
                        js.push_str(&format!("{}{}.setAttribute({:?}, {:?});\n", ind, el, attr.name, val));
                    }
                    _ => {
                        // Unknown attr: try as style first, else setAttribute
                        let css_name = attr.name.replace("_", "-");
                        js.push_str(&format!("{}{}.style['{}'] = '{}';\n", ind, el, css_name, val));
                    }
                }
            }
            AttrValue::Expr(expr) => {
                match attr.name.as_str() {
                    "bind" => {
                        js.push_str(&format!("{}Binding.twoWay({}, state, {:?}, 'input');\n", ind, el, expr));
                    }
                    "text" | "value" => {
                        // For computed expressions, use watch-based approach
                        if is_simple_key(expr) {
                            js.push_str(&format!("{}Binding.oneWay({}, 'textContent', state, {:?});\n", ind, el, expr));
                        } else {
                            let js_expr = kyle_to_js_expr(expr);
                            js.push_str(&format!("{}const __upd = () => {{ {}.textContent = {}; }};\n", ind, el, js_expr));
                            js.push_str(&format!("{}__upd();\n", ind));
                            js.push_str(&format!("{}state.watch('count', __upd);\n", ind));
                        }
                    }
                    "tpl" => {
                        js.push_str(&format!("{}applyStyle({}, state.get({:?}));\n", ind, el, expr));
                    }
                    "animation" => {
                        js.push_str(&format!("{}applyAnimation({}, state.get({:?}));\n", ind, el, expr));
                    }
                    "checked" => {
                        js.push_str(&format!("{}Binding.oneWay({}, 'checked', state, {:?});\n", ind, el, expr));
                    }
                    "disabled" => {
                        js.push_str(&format!("{}Binding.oneWay({}, 'disabled', state, {:?});\n", ind, el, expr));
                    }
                    "click" | "change" | "input" | "mouse_enter" | "mouse_leave"
                    | "focus" | "blur" | "keydown" | "keyup" | "submit" | "scroll"
                    | "dblclick" | "context_menu" | "mouse_down" | "mouse_up"
                    | "mouse_move" | "touch_start" | "touch_end" | "touch_move" => {}
                    _ => {
                        let css_name = attr.name.replace("_", "-");
                        if is_simple_key(expr) {
                            js.push_str(&format!("{}{}.style['{}'] = state.get({:?});\n", ind, el, css_name, expr));
                        } else {
                            js.push_str(&format!("{}const __upd = () => {{ {}.style['{}'] = {}; }};\n", ind, el, css_name, expr));
                            js.push_str(&format!("{}__upd();\n", ind));
                        }
                    }
                }
            }
            AttrValue::Flag => {
                js.push_str(&format!("{}{}.setAttribute({:?}, '');\n", ind, el, attr.name));
            }
        }
    }
}

/// Map style attribute names to CSS property strings (quoted)
fn style_attr_to_css(name: &str) -> Option<String> {
    let prop = match name {
        "font_size" => "fontSize",
        "font_weight" => "fontWeight",
        "font_family" => "fontFamily",
        "color" => "color",
        "background" | "bg" => "background",
        "background_color" => "backgroundColor",
        "padding" => "padding",
        "margin" => "margin",
        "width" | "w" => "width",
        "height" | "h" => "height",
        "min_width" => "minWidth",
        "max_width" => "maxWidth",
        "min_height" => "minHeight",
        "max_height" => "maxHeight",
        "border_radius" => "borderRadius",
        "border" => "border",
        "opacity" => "opacity",
        "overflow" => "overflow",
        "display" => "display",
        "gap" => "gap",
        "z_index" => "zIndex",
        "cursor" => "cursor",
        "text_align" => "textAlign",
        "line_height" => "lineHeight",
        "letter_spacing" => "letterSpacing",
        "transform" => "transform",
        "transition" => "transition",
        "box_shadow" | "shadow" => "boxShadow",
        "flex" => "flex",
        "flex_grow" => "flexGrow",
        "flex_shrink" => "flexShrink",
        "flex_basis" => "flexBasis",
        "flex_direction" => "flexDirection",
        "align_items" => "alignItems",
        "align_self" => "alignSelf",
        "justify_content" => "justifyContent",
        "position" => "position",
        "top" => "top",
        "right" => "right",
        "bottom" => "bottom",
        "left" => "left",
        _ => return None,
    };
    Some(format!("'{}'", prop))
}

/// Convert a style attribute value to a JS expression
fn attr_style_value(name: &str, val: &str) -> String {
    let v = val.trim().trim_matches('"');
    // Numbers -> add px for size-related properties
    let needs_px = matches!(name, "font_size" | "border_radius" | "gap" | "padding"
        | "margin" | "width" | "height" | "min_width" | "max_width"
        | "min_height" | "max_height" | "line_height" | "letter_spacing"
        | "top" | "right" | "bottom" | "left");
    if needs_px && v.chars().all(|c| c.is_ascii_digit() || c == '.') {
        return format!("'{}px'", v);
    }
    format!("'{}'", v)
}

/// Check if an expression is a simple state key (single identifier)
fn is_simple_key(expr: &str) -> bool {
    let trimmed = expr.trim();
    !trimmed.contains(' ') && !trimmed.contains('"') && !trimmed.contains('+')
        && !trimmed.contains('(') && !trimmed.contains(')')
}

/// Convert layout value to (alignItems, justifyContent)
fn layout_to_flex(layout: &str) -> (&str, &str) {
    match layout.trim().to_lowercase().as_str() {
        "center" => ("center", "center"),
        "start" => ("flex-start", "flex-start"),
        "end" => ("flex-end", "flex-end"),
        "stretch" => ("stretch", "stretch"),
        "top" | "start_top" => ("flex-start", "flex-start"),
        "bottom" | "end_bottom" => ("flex-end", "flex-end"),
        "center_x" | "hcenter" => ("center", "flex-start"),
        "center_y" | "vcenter" => ("flex-start", "center"),
        "space_between" => ("center", "space-between"),
        "space_around" => ("center", "space-around"),
        _ => ("", ""),
    }
}

fn gen_events(attrs: &[UiAttr], js: &mut String, indent: usize, el: &str) {
    let ind = " ".repeat(indent + 2);
    for attr in attrs {
        let event_name = match attr.name.as_str() {
            "click" => "click",
            "change" => "change",
            "input" => "input",
            "mouse_enter" => "mouseenter",
            "mouse_leave" => "mouseleave",
            "focus" => "focus",
            "blur" => "blur",
            "keydown" => "keydown",
            "keyup" => "keyup",
            "submit" => "submit",
            "scroll" => "scroll",
            "dblclick" => "dblclick",
            "context_menu" => "contextmenu",
            "mouse_down" => "mousedown",
            "mouse_up" => "mouseup",
            "mouse_move" => "mousemove",
            "touch_start" => "touchstart",
            "touch_end" => "touchend",
            "touch_move" => "touchmove",
            _ => continue,
        };
        if let AttrValue::Expr(handler) = &attr.value {
            js.push_str(&format!("{}{}.addEventListener({:?}, (e) => {{ {}(createKyleEvent(e)); }});\n", ind, el, event_name, handler));
        }
    }
}

fn js_tag(tag: &ComponentTag) -> &str {
    match tag {
        ComponentTag::View | ComponentTag::Column | ComponentTag::Row
        | ComponentTag::Stack | ComponentTag::Container => "div",
        ComponentTag::Text | ComponentTag::Label => "span",
        ComponentTag::Button | ComponentTag::IconButton => "button",
        ComponentTag::TextField => "input",
        ComponentTag::PasswordField => "input",
        ComponentTag::TextArea => "textarea",
        ComponentTag::Checkbox => "input",
        ComponentTag::Radio => "input",
        ComponentTag::Image | ComponentTag::Icon => "img",
        ComponentTag::Link => "a",
        ComponentTag::List => "ul",
        ComponentTag::Form => "form",
        ComponentTag::Dialog => "dialog",
        ComponentTag::Canvas => "canvas",
        ComponentTag::Video => "video",
        ComponentTag::Audio => "audio",
        ComponentTag::Select => "select",
        ComponentTag::Slider => "input",
        ComponentTag::Switch => "input",
        ComponentTag::Progress => "progress",
        ComponentTag::Spinner => "div",
        _ => "div",
    }
}

/// Generate HTML shell from component config
fn generate_html() -> String {
    r#"<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Kyle App</title>
</head>
<body>
    <div id="app"></div>
    <script type="module">
        import { render } from './ui-runtime.js';
        const app = document.getElementById('app');
        const result = render();
        app.appendChild(result.element);
    </script>
</body>
</html>
"#.to_string()
}

// ── Style Generator ──────────────────────────────────────────────

fn generate_styles(styles: &[StyleDecl]) -> String {
    let mut js = String::new();

    let mut has_media = false;
    js.push_str("const _style_data = {\n");
    for decl in styles {
        match decl {
            StyleDecl::Style { name, props, media, .. }
            | StyleDecl::Layout { name, props, media, .. }
            | StyleDecl::Template { name, props, media, .. } => {
                js.push_str(&format!("  '{}': {{\n", name));
                for prop in props {
                    let css_prop = to_css_name(&prop.name);
                    let css_val = to_css_value(&prop.name, &prop.value);
                    js.push_str(&format!("    '{}': '{}',\n", css_prop, css_val));
                }
                for mq in media {
                    has_media = true;
                    let mq_cond = to_media_condition(&mq.condition);
                    js.push_str(&format!("    '{}': {{\n", mq_cond));
                    for prop in &mq.props {
                        let css_prop = to_css_name(&prop.name);
                        let css_val = to_css_value(&prop.name, &prop.value);
                        js.push_str(&format!("      '{}': '{}',\n", css_prop, css_val));
                    }
                    js.push_str("    },\n");
                }
                js.push_str("  },\n");
            }
            StyleDecl::Theme { name, props } => {
                js.push_str(&format!("  'theme:{}': {{\n", name));
                for prop in props {
                    js.push_str(&format!("    '{}': '{}',\n", prop.name, prop.value));
                }
                js.push_str("  },\n");
            }
        }
    }
    js.push_str("};\n\n");

    // Export styles
    js.push_str("export const styles = _style_data;\n\n");

    js.push_str("export function applyStyle(el, styleName) {\n");
    js.push_str("  const s = _style_data[styleName];\n");
    js.push_str("  if (!s) return;\n");
    js.push_str("  const base = {};\n");
    js.push_str("  const mediaQueries = {};\n");
    js.push_str("  for (const [key, val] of Object.entries(s)) {\n");
    js.push_str("    if (key.startsWith('@media')) {\n");
    js.push_str("      mediaQueries[key] = val;\n");
    js.push_str("    } else {\n");
    js.push_str("      base[key] = val;\n");
    js.push_str("    }\n");
    js.push_str("  }\n");
    js.push_str("  for (const [prop, val] of Object.entries(base)) {\n");
    js.push_str("    el.style[prop] = val;\n");
    js.push_str("  }\n");
    js.push_str("  for (const [mq, rules] of Object.entries(mediaQueries)) {\n");
    js.push_str("    const mql = window.matchMedia(mq.replace('@media ', ''));\n");
    js.push_str("    const apply = () => {\n");
    js.push_str("      if (mql.matches) {\n");
    js.push_str("        for (const [prop, val] of Object.entries(rules)) {\n");
    js.push_str("          el.style[prop] = val;\n");
    js.push_str("        }\n");
    js.push_str("      }\n");
    js.push_str("    };\n");
    js.push_str("    apply();\n");
    js.push_str("    mql.addEventListener('change', apply);\n");
    js.push_str("  }\n");
    js.push_str("}\n\n");

    js
}

fn to_css_name(prop: &str) -> &str {
    match prop {
        "background" => "background",
        "color" => "color",
        "font_size" => "fontSize",
        "font_weight" => "fontWeight",
        "font_family" => "fontFamily",
        "line_height" => "lineHeight",
        "letter_spacing" => "letterSpacing",
        "text_align" => "textAlign",
        "border_radius" => "borderRadius",
        "border" => "border",
        "border_top" => "borderTop",
        "border_right" => "borderRight",
        "border_bottom" => "borderBottom",
        "border_left" => "borderLeft",
        "padding" => "padding",
        "margin" => "margin",
        "width" => "width",
        "height" => "height",
        "min_width" => "minWidth",
        "max_width" => "maxWidth",
        "min_height" => "minHeight",
        "max_height" => "maxHeight",
        "opacity" => "opacity",
        "cursor" => "cursor",
        "overflow" => "overflow",
        "display" => "display",
        "gap" => "gap",
        "z_index" => "zIndex",
        "shadow" => "boxShadow",
        "transform" => "transform",
        "transition" => "transition",
        "flex_direction" => "flexDirection",
        "flex_grow" => "flexGrow",
        "flex_shrink" => "flexShrink",
        "flex_basis" => "flexBasis",
        "align_items" => "alignItems",
        "justify_content" => "justifyContent",
        _ => prop, // passthrough
    }
}

fn to_css_value(prop: &str, val: &str) -> String {
    let val = val.trim();
    // Handle Color(...) function
    if val.starts_with("Color(") {
        // Color("#FF0000") or Color(r, g, b, a)
        let inner = val.trim_start_matches("Color(").trim_end_matches(')');
        // Check if it's a hex string
        let inner = inner.trim().trim_matches('"');
        if inner.starts_with('#') {
            return inner.to_string();
        }
        // Handle Color.from_hex, Color.from_rgba, etc.
        return "#333333".to_string();
    }
    // Handle Spacing(...) function
    if val.starts_with("Spacing") {
        // Spacing.all(12) or Spacing(12, 24, 12, 24)
        if let Some(num) = val.split(|c: char| !c.is_ascii_digit()).find(|s| !s.is_empty()) {
            return format!("{}px", num);
        }
        return "0".to_string();
    }
    // Handle enum types: FontWeight.Bold → "bold", etc.
    let normalized = val.trim();
    if normalized.starts_with("FontWeight.") {
        return match normalized.trim_start_matches("FontWeight.") {
            "Thin" => "100",
            "Light" => "300",
            "Normal" => "400",
            "Medium" => "500",
            "SemiBold" => "600",
            "Bold" => "700",
            "Black" => "900",
            _ => "400",
        }.to_string();
    }
    if normalized.starts_with("TextAlign.") {
        return match normalized.trim_start_matches("TextAlign.") {
            "Left" => "left",
            "Center" => "center",
            "Right" => "right",
            "Justify" => "justify",
            _ => "left",
        }.to_string();
    }
    if normalized.starts_with("Display.") {
        return match normalized.trim_start_matches("Display.") {
            "Flex" => "flex",
            "Grid" => "grid",
            "None" => "none",
            "Block" => "block",
            "Inline" => "inline",
            _ => "flex",
        }.to_string();
    }
    if normalized.starts_with("FlexDirection.") {
        return match normalized.trim_start_matches("FlexDirection.") {
            "Row" => "row",
            "Column" | "Col" => "column",
            "RowReverse" => "row-reverse",
            "ColumnReverse" => "column-reverse",
            _ => "column",
        }.to_string();
    }
    if normalized.starts_with("Alignment.") || normalized.starts_with("Align") {
        return match normalized.trim_start_matches("Alignment.").trim_start_matches("Align") {
            "Center" => "center",
            "Start" | "FlexStart" => "flex-start",
            "End" | "FlexEnd" => "flex-end",
            "Stretch" => "stretch",
            "SpaceBetween" => "space-between",
            "SpaceAround" => "space-around",
            "SpaceEvenly" => "space-evenly",
            "Baseline" => "baseline",
            _ => "center",
        }.to_string();
    }
    if normalized.starts_with("Cursor.") {
        return match normalized.trim_start_matches("Cursor.") {
            "Pointer" => "pointer",
            "Default" => "default",
            "Text" => "text",
            "Wait" => "wait",
            "Crosshair" => "crosshair",
            "NotAllowed" => "not-allowed",
            "Grab" => "grab",
            "Grabbing" => "grabbing",
            _ => "default",
        }.to_string();
    }
    if normalized.starts_with("Overflow.") {
        return match normalized.trim_start_matches("Overflow.") {
            "Visible" => "visible",
            "Hidden" => "hidden",
            "Scroll" => "scroll",
            "Auto" => "auto",
            _ => "visible",
        }.to_string();
    }
    // Numeric size props
    if prop == "font_size" || prop == "border_radius" || prop == "gap"
        || prop == "line_height" || prop == "letter_spacing"
    {
        if val.chars().all(|c| c.is_ascii_digit() || c == '.') {
            return format!("{}px", val);
        }
    }
    // Direct hex colors
    if val.starts_with('#') || val == "white" || val == "black" || val == "transparent" {
        return val.to_string();
    }
    val.to_string()
}

fn to_media_condition(cond: &str) -> String {
    let c = cond.replace('_', "-");
    if c.contains(':') {
        format!("@media ({})", c)
    } else {
        format!("@media ({})", c)
    }
}

// ── Animation Generator ──────────────────────────────────────────

fn generate_animations(animations: &[AnimDecl]) -> String {
    let mut js = String::new();

    if animations.is_empty() {
        js.push_str("export const animations = {};\n\n");
        js.push_str("export function applyAnimation(el, animName) {\n");
        js.push_str("  const a = animations[animName];\n");
        js.push_str("  if (!a) return;\n");
        js.push_str("  el.animate(a.keyframes, a.options);\n");
        js.push_str("}\n\n");
        return js;
    }

    js.push_str("export const animations = {\n");
    for anim in animations {
        js.push_str(&format!("  '{}': {{\n", anim.name));
        js.push_str("    keyframes: [\n");

        let mut from = String::new();
        let mut to = String::new();
        let mut duration = 300i64;
        let mut easing = "ease".to_string();
        let mut iterations = 1i64;
        let mut delay = 0i64;
        let mut direction = "normal".to_string();
        let mut fill = "none".to_string();

        for prop in &anim.props {
            let v = prop.value.trim();
            match prop.name.as_str() {
                "duration" => { if let Ok(n) = v.parse::<i64>() { duration = n; } }
                "easing" => easing = to_js_easing(v),
                "delay" => { if let Ok(n) = v.parse::<i64>() { delay = n; } }
                "iterations" => { if let Ok(n) = v.parse::<i64>() { iterations = n; } }
                "direction" => direction = v.trim_matches('"').to_string(),
                "fill_mode" => fill = v.trim_matches('"').to_string(),
                "from" => from = parse_anim_state(v),
                "to" => to = parse_anim_state(v),
                _ => {}
            }
        }

        if !from.is_empty() {
            js.push_str(&format!("      {},\n", from));
        }
        if !to.is_empty() {
            js.push_str(&format!("      {},\n", to));
        }

        js.push_str("    ],\n");
        js.push_str("    options: {\n");
        js.push_str(&format!("      duration: {},\n", duration));
        js.push_str(&format!("      easing: '{}',\n", easing));
        js.push_str(&format!("      iterations: {},\n", iterations));
        if delay > 0 { js.push_str(&format!("      delay: {},\n", delay)); }
        if direction != "normal" { js.push_str(&format!("      direction: '{}',\n", direction)); }
        if fill != "none" { js.push_str(&format!("      fill: '{}',\n", fill)); }
        js.push_str("    },\n");
        js.push_str("  },\n");
    }
    js.push_str("};\n\n");

    js.push_str("export function applyAnimation(el, animName) {\n");
    js.push_str("  const a = animations[animName];\n");
    js.push_str("  if (!a) return;\n");
    js.push_str("  _a11y.animate(el, a.keyframes, a.options);\n");
    js.push_str("}\n\n");

    js
}

fn parse_anim_state(s: &str) -> String {
    let s = s.trim();
    if !s.starts_with("AnimationState(") {
        return "{}".to_string();
    }
    let inner = s.trim_start_matches("AnimationState(").trim_end_matches(')');
    let mut props = Vec::new();
    for part in inner.split(',') {
        let part = part.trim();
        if let Some(eq) = part.find(':') {
            let key = &part[..eq].trim();
            let val = &part[eq+1..].trim();
            let css_key = anim_prop_to_css(key);
            props.push(format!("'{}': {}", css_key, val));
        }
    }
    format!("{{{}}}", props.join(", "))
}

fn anim_prop_to_css(prop: &str) -> &str {
    match prop {
        "opacity" => "opacity",
        "translate_x" => "transform",
        "translate_y" => "transform",
        "scale_x" => "transform",
        "scale_y" => "transform",
        "rotate" => "transform",
        "background" => "backgroundColor",
        "color" => "color",
        "border_radius" => "borderRadius",
        "shadow" => "boxShadow",
        "width" => "width",
        "height" => "height",
        _ => prop,
    }
}

fn to_js_easing(easing: &str) -> String {
    match easing.trim() {
        "Easing.Linear" => "linear",
        "Easing.Ease" => "ease",
        "Easing.EaseIn" => "ease-in",
        "Easing.EaseOut" => "ease-out",
        "Easing.EaseInOut" => "ease-in-out",
        "Easing.EaseInSine" => "cubic-bezier(0.47, 0, 0.745, 0.715)",
        "Easing.EaseOutSine" => "cubic-bezier(0.39, 0.575, 0.565, 1)",
        "Easing.EaseInCubic" => "cubic-bezier(0.55, 0.055, 0.675, 0.19)",
        "Easing.EaseOutCubic" => "cubic-bezier(0.215, 0.61, 0.355, 1)",
        "Easing.Bounce" => "cubic-bezier(0.68, -0.55, 0.265, 1.55)",
        _ => "ease",
    }.to_string()
}

/// Translate a Kyle code block (@(...)) to basic JavaScript.
/// This is a temporary solution until the WASM bridge is implemented.
fn translate_kyle_block_to_js(block: &str) -> String {
    let mut js = String::new();
    let mut open_fns: Vec<usize> = Vec::new(); // track indentation of open functions
    let mut last_indent: Option<usize> = None;

    for raw_line in block.lines() {
        let indent = raw_line.len() - raw_line.trim_start().len();
        let line = raw_line.trim();
        last_indent = Some(indent);

        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        // Variable declaration: "count: ^i32 = 0" → "state.set('count', 0);"
        if line.contains('=') && !line.starts_with("fn ") && line.contains(':') {
            if let Some(colon_pos) = line.find(':') {
                let before_colon = line[..colon_pos].trim();
                let after_colon = line[colon_pos + 1..].trim();
                if let Some(eq_pos) = after_colon.find('=') {
                    let name = before_colon;
                    let ann = after_colon[..eq_pos].trim();
                    let value = after_colon[eq_pos + 1..].trim();
                    // Verify it looks like a type annotation
                    if ann.chars().all(|c| c.is_alphanumeric() || c == '_' || c == '^' || c == '&') {
                        js.push_str(&format!("state.set('{}', {});\n", name, value));
                    }
                }
            }
            continue; // skip further processing
        }

        // Function definition: "fn name(args):" → "const name = (args) => {"
        if line.starts_with("fn ") {
            let rest = line.trim_start_matches("fn ").trim();
            if let Some(paren_pos) = rest.find('(') {
                let name = rest[..paren_pos].trim();
                let params_end = rest.rfind(')').unwrap_or(rest.len());
                let params = &rest[paren_pos..=params_end];
                // Strip trailing colon from params
                let params = params.trim_end_matches(':');
                js.push_str(&format!("const {} = {} => {{\n", name, params));
                open_fns.push(indent);
            }
            continue;
        }

        // Close functions when indentation decreases or matches parent
        while let Some(&fn_indent) = open_fns.last() {
            if indent <= fn_indent && !open_fns.is_empty() {
                js.push_str("};\n");
                open_fns.pop();
            } else {
                break;
            }
        }

        // Function body: "count = count + 1" → "state.set('count', state.get('count') + 1);"
        if line.contains('=') && !line.contains("==") {
            if let Some(eq_pos) = line.find('=') {
                let target = line[..eq_pos].trim();
                let value = line[eq_pos + 1..].trim();
                if !target.contains('(') && !target.contains(' ') && !target.starts_with("state.") {
                    let js_value = value.replace(&target, &format!("state.get('{}')", target));
                    js.push_str(&format!("  state.set('{}', {});\n", target, js_value));
                } else {
                    js.push_str(&format!("  {} = {};\n", target, value));
                }
            }
            continue;
        }

        // Plain expression
        js.push_str(&format!("{}\n", line));
    }

    // Close any remaining open functions
    while !open_fns.is_empty() {
        js.push_str("};\n");
        open_fns.pop();
    }

    js
}

/// Translate a Kyle expression to JS, replacing state vars and method names.
fn kyle_to_js_expr(expr: &str) -> String {
    let mut result = expr.to_string();
    // Replace .to_str() with .toString()
    result = result.replace(".to_str()", ".toString()");
    result = result.replace(".to_string()", ".toString()");
    // Replace common Kyle variable references with state.get(...)
    // We handle known state keys from the code blocks
    result = result.replace("count", "state.get('count')");
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_web_backend_generates_js() {
        let backend = WebBackend::new();
        let program = UiProgram {
            view_paths: vec![],
            code_blocks: vec![],
            styles: vec![],
            animations: vec![],
            body: vec![UiNode::SelfClosing {
                tag: ComponentTag::Text,
                attrs: vec![UiAttr {
                    name: "value".to_string(),
                    value: AttrValue::String("Hello".to_string()),
                }],
            }],
        };
        let output = backend.generate(&program);
        assert!(output.files.len() == 1);
        assert!(output.files[0].content.contains("createElement"));
        assert!(output.files[0].content.contains("Hello"));
        assert!(output.html_shell.is_some());
        let html = output.html_shell.unwrap();
        assert!(html.contains("<script type=\"module\">"));
    }

    #[test]
    fn test_style_generation() {
        let styles = vec![StyleDecl::Style {
            component: "button".to_string(),
            name: "Primary".to_string(),
            props: vec![
                StyleProp { name: "background".to_string(), value: "Color(\"#0066FF\")".to_string() },
                StyleProp { name: "color".to_string(), value: "Color(\"#FFFFFF\")".to_string() },
                StyleProp { name: "border_radius".to_string(), value: "8".to_string() },
            ],
            media: vec![],
        }];
        let js = generate_styles(&styles);
        assert!(js.contains("Primary"));
        assert!(js.contains("export function applyStyle"));
    }

    #[test]
    fn test_animation_generation() {
        let anims = vec![AnimDecl {
            component: "view".to_string(),
            name: "FadeIn".to_string(),
            props: vec![
                StyleProp { name: "duration".to_string(), value: "300".to_string() },
                StyleProp { name: "easing".to_string(), value: "Easing.EaseOut".to_string() },
                StyleProp { name: "from".to_string(), value: "AnimationState(opacity: 0.0)".to_string() },
                StyleProp { name: "to".to_string(), value: "AnimationState(opacity: 1.0)".to_string() },
            ],
        }];
        let js = generate_animations(&anims);
        assert!(js.contains("export const animations"));
        assert!(js.contains("export function applyAnimation"));
    }
}
