use crate::ast::*;

/// Generate JavaScript code from a KyxFile AST.
pub fn generate(file: &KyxFile) -> String {
    let mut js = String::new();
    js.push_str("// Generated by Kyle UI Compiler\n");
    js.push_str("// Target: Web (JS/DOM)\n\n");

    // Generate styles
    let style_js = crate::style_gen::generate_styles(&file.styles);
    js.push_str(&style_js);

    // Generate component function
    js.push_str("function render() {\n");
    js.push_str("  const el = document.createDocumentFragment();\n");

    for node in &file.body {
        gen_node(node, &mut js, 2);
    }

    js.push_str("  return el;\n");
    js.push_str("}\n\n");

    // Export
    js.push_str("if (typeof module !== 'undefined' && module.exports) {\n");
    js.push_str("  module.exports = { render, styles };\n");
    js.push_str("}\n");

    js
}

fn gen_node(node: &KyxNode, js: &mut String, indent: usize) {
    let ind = " ".repeat(indent);
    let _ind1 = " ".repeat(indent + 2);

    match node {
        KyxNode::Element { tag, attrs, children } => {
            let tag_js = js_tag(tag);
            js.push_str(&format!("{}const _el = document.createElement('{}');\n", ind, tag_js));
            gen_attrs(attrs, js, indent);
            for child in children {
                gen_node(child, js, indent + 2);
                js.push_str(&format!("{}_el.appendChild(_child);\n", ind));
            }
            // Event listeners
            gen_events(attrs, js, indent);
            js.push_str(&format!("{}return _el;\n", ind));
        }
        KyxNode::SelfClosing { tag, attrs } => {
            let tag_js = js_tag(tag);
            js.push_str(&format!("{}const _el = document.createElement('{}');\n", ind, tag_js));
            gen_attrs(attrs, js, indent);
            gen_events(attrs, js, indent);
            js.push_str(&format!("{}_child = _el;\n", ind));
        }
        KyxNode::Slot { name, fallback } => {
            js.push_str(&format!("{}// Slot: {}\n", ind, name));
            if !fallback.is_empty() {
                for child in fallback {
                    gen_node(child, js, indent);
                }
            }
        }
        KyxNode::If { condition, then_branch, else_branch } => {
            js.push_str(&format!("{}if ({}) {{\n", ind, condition));
            for child in then_branch {
                gen_node(child, js, indent + 2);
            }
            if !else_branch.is_empty() {
                js.push_str(&format!("{}}} else {{\n", ind));
                for child in else_branch {
                    gen_node(child, js, indent + 2);
                }
            }
            js.push_str(&format!("{}}}\n", ind));
        }
        KyxNode::For { item, list, body } => {
            js.push_str(&format!("{}for (const {} of {}) {{\n", ind, item, list));
            for child in body {
                gen_node(child, js, indent + 2);
            }
            js.push_str(&format!("{}}}\n", ind));
        }
        KyxNode::Match { expr, cases } => {
            js.push_str(&format!("{}switch ({}) {{\n", ind, expr));
            for case in cases {
                js.push_str(&format!("{}  case {}:\n", ind, case.pattern));
                for child in &case.body {
                    gen_node(child, js, indent + 4);
                }
                js.push_str(&format!("{}    break;\n", ind));
            }
            js.push_str(&format!("{}}}\n", ind));
        }
        KyxNode::Expr(expr) => {
            js.push_str(&format!("{}// Expression: {}\n", ind, expr));
            js.push_str(&format!("{}{}\n", ind, expr));
        }
        KyxNode::CodeBlock(code) => {
            for line in code.lines() {
                js.push_str(&format!("{}// Kyle: {}\n", ind, line));
            }
        }
        KyxNode::Text(text) => {
            js.push_str(&format!("{}_child = document.createTextNode({:?});\n", ind, text));
        }
    }
}

fn gen_attrs(attrs: &[KyxAttr], js: &mut String, indent: usize) {
    let ind = " ".repeat(indent + 2);
    for attr in attrs {
        match &attr.value {
            AttrValue::String(val) => {
                match attr.name.as_str() {
                    "tpl" => {
                        js.push_str(&format!("{}applyStyle(_el, {:?});\n", ind, val));
                    }
                    "style" => {
                        js.push_str(&format!("{}applyStyle(_el, {:?});\n", ind, val));
                    }
                    "text" | "value" | "label" => {
                        js.push_str(&format!("{}_el.textContent = {:?};\n", ind, val));
                    }
                    "class" | "id" => {
                        js.push_str(&format!("{}_el.setAttribute({:?}, {:?});\n", ind, attr.name, val));
                    }
                    _ => {
                        js.push_str(&format!("{}_el.setAttribute({:?}, {:?});\n", ind, attr.name, val));
                    }
                }
            }
            AttrValue::Expr(expr) => {
                match attr.name.as_str() {
                    "bind" => {
                        js.push_str(&format!("{}_el.value = {};\n", ind, expr));
                        js.push_str(&format!("{}_el.addEventListener('input', () => {{ {} = _el.value; }});\n", ind, expr));
                    }
                    "text" | "value" => {
                        js.push_str(&format!("{}_el.textContent = {};\n", ind, expr));
                    }
                    "tpl" => {
                        js.push_str(&format!("{}applyStyle(_el, {});\n", ind, expr));
                    }
                    _ => {
                        js.push_str(&format!("{}// attr {} = {}\n", ind, attr.name, expr));
                    }
                }
            }
            AttrValue::Flag => {
                js.push_str(&format!("{}_el.setAttribute({:?}, '');\n", ind, attr.name));
            }
        }
    }
}

fn gen_events(attrs: &[KyxAttr], js: &mut String, indent: usize) {
    let ind = " ".repeat(indent + 2);
    for attr in attrs {
        let event_name = match attr.name.as_str() {
            "click" => "click",
            "change" => "change",
            "input" => "input",
            "mouse_enter" => "mouseenter",
            "mouse_leave" => "mouseleave",
            "focus" => "focus",
            "blur" => "blur",
            "keydown" => "keydown",
            "submit" => "submit",
            "scroll" => "scroll",
            _ => continue,
        };
        if let AttrValue::Expr(handler) = &attr.value {
            js.push_str(&format!("{}_el.addEventListener({:?}, () => {{ {}(); }});\n", ind, event_name, handler));
        }
    }
}

fn js_tag(tag: &str) -> &str {
    match tag.to_lowercase().as_str() {
        "view" | "column" | "row" | "stack" | "container" => "div",
        "text" | "label" => "span",
        "button" | "iconbutton" => "button",
        "textfield" | "passwordfield" | "textarea" => "input",
        "checkbox" => "input",
        "radio" => "input",
        "image" | "icon" => "img",
        "link" => "a",
        "list" => "ul",
        "form" => "form",
        "dialog" => "dialog",
        "canvas" => "canvas",
        "video" => "video",
        "audio" => "audio",
        _ => "div",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser;

    #[test]
    fn test_generate_simple() {
        let source = r#"<text value="Hello" />"#;
        let file = parser::parse(source).unwrap();
        let js = generate(&file);
        assert!(js.contains("createElement"));
        assert!(js.contains("Hello"));
    }

    #[test]
    fn test_generate_with_events() {
        let source = r#"<button text="Click" click=@handle_click />"#;
        let file = parser::parse(source).unwrap();
        let js = generate(&file);
        assert!(js.contains("addEventListener"));
        assert!(js.contains("click"));
    }
}
