use crate::ast::*;

/// Generate JavaScript code from a KyxFile AST.
pub fn generate(file: &KyxFile) -> String {
    let mut js = String::new();
    js.push_str("// Generated by Kyle UI Compiler\n");
    js.push_str("// Target: Web (JS/DOM)\n\n");

    // Include reactivity and router runtimes
    js.push_str("const { ReactiveState, Binding, createKyleEvent } = require('./reactivity.js');\n");
    js.push_str("const { Router, routeParams } = require('./router.js');\n");
    js.push_str("const { A11yManager } = require('./a11y.js');\n");
    js.push_str("const _a11y = new A11yManager();\n\n");

    // Generate styles
    let style_js = crate::style_gen::generate_styles(&file.styles);
    js.push_str(&style_js);

    // Generate animations
    let anim_js = crate::anim_gen::generate_animations(&file.animations);
    js.push_str(&anim_js);

    // Determine component name from view path
    let comp_name = if let Some(path) = file.view_paths.first() {
        let name = path.trim_start_matches('/').replace('/', "_").replace(&['{', '}', '-'][..], "");
        if name.is_empty() { "home".to_string() } else { name }
    } else {
        "component".to_string()
    };

    // Generate component function
    js.push_str(&format!("function render{}(container, initialState = {{}}) {{\n", comp_name));
    js.push_str("  const state = new ReactiveState(initialState);\n");
    js.push_str("  const el = document.createDocumentFragment();\n");

    for node in &file.body {
        gen_node(node, &mut js, 2, "el");
    }

    js.push_str("  return { element: el, state };\n");
    js.push_str("}\n\n");

    // Route registration (for views with view("/path"))
    if !file.view_paths.is_empty() {
        js.push_str("// Auto-register routes\n");
        js.push_str("if (typeof window !== 'undefined') {\n");
        js.push_str("  if (!window.__KYLE_ROUTES) window.__KYLE_ROUTES = {};\n");
        for path in &file.view_paths {
            js.push_str(&format!("  window.__KYLE_ROUTES[{:?}] = render{};\n", path, comp_name));
        }
        js.push_str("}\n\n");
    }

    // Export
    js.push_str("if (typeof module !== 'undefined' && module.exports) {\n");
    js.push_str(&format!("  module.exports = {{ render: render{}, styles, animations }};\n", comp_name));
    js.push_str("}\n");

    js
}

fn gen_node(node: &KyxNode, js: &mut String, indent: usize, parent: &str) {
    let ind = " ".repeat(indent);
    let ind2 = " ".repeat(indent + 2);

    match node {
        KyxNode::Element { tag, attrs, children } => {
            let tag_js = js_tag(tag);
            js.push_str(&format!("{}const _el = document.createElement('{}');\n", ind, tag_js));
            gen_attrs(attrs, js, indent);
            gen_events(attrs, js, indent);
            // ARIA auto-generation
            js.push_str(&format!("{}A11yManager.applyAria(_el, {:?});\n", " ".repeat(indent + 2), tag));
            for child in children {
                gen_node(child, js, indent + 2, "_el");
            }
            js.push_str(&format!("{}{}.appendChild(_el);\n", ind, parent));
        }
        KyxNode::SelfClosing { tag, attrs } => {
            let tag_js = js_tag(tag);
            js.push_str(&format!("{}const _el = document.createElement('{}');\n", ind, tag_js));
            gen_attrs(attrs, js, indent);
            gen_events(attrs, js, indent);
            js.push_str(&format!("{}A11yManager.applyAria(_el, {:?});\n", " ".repeat(indent + 2), tag));
            js.push_str(&format!("{}{}.appendChild(_el);\n", ind, parent));
        }
        KyxNode::Slot { name, fallback } => {
            js.push_str(&format!("{}// Slot: {}\n", ind, name));
            if !fallback.is_empty() {
                for child in fallback {
                    gen_node(child, js, indent, parent);
                }
            }
        }
        KyxNode::If { condition, then_branch, else_branch } => {
            js.push_str(&format!("{}if ({}) {{\n", ind, condition));
            for child in then_branch {
                gen_node(child, js, indent + 4, parent);
            }
            if !else_branch.is_empty() {
                js.push_str(&format!("{}}} else {{\n", ind));
                for child in else_branch {
                    gen_node(child, js, indent + 4, parent);
                }
            }
            js.push_str(&format!("{}}}\n", ind));
        }
        KyxNode::For { item, list, body } => {
            js.push_str(&format!("{}for (const {} of {}) {{\n", ind, item, list));
            for child in body {
                gen_node(child, js, indent + 4, parent);
            }
            js.push_str(&format!("{}}}\n", ind));
        }
        KyxNode::Match { expr, cases } => {
            js.push_str(&format!("{}switch ({}) {{\n", ind, expr));
            for case in cases {
                js.push_str(&format!("{}  case {}:\n", ind, case.pattern));
                for child in &case.body {
                    gen_node(child, js, indent + 8, parent);
                }
                js.push_str(&format!("{}    break;\n", ind));
            }
            js.push_str(&format!("{}}}\n", ind));
        }
        KyxNode::Expr(e) => {
            js.push_str(&format!("{}// Expression: {}\n", ind, e));
            js.push_str(&format!("{}{}\n", ind, e));
        }
        KyxNode::CodeBlock(_code) => {
            // Code blocks are handled at file level — skip in body
        }
        KyxNode::Text(text) => {
            js.push_str(&format!("{}{}.appendChild(document.createTextNode({:?}));\n", ind, parent, text));
        }
    }
}

fn gen_attrs(attrs: &[KyxAttr], js: &mut String, indent: usize) {
    let ind = " ".repeat(indent + 2);
    for attr in attrs {
        match &attr.value {
            AttrValue::String(val) => {
                match attr.name.as_str() {
                    "tpl" | "style" => {
                        js.push_str(&format!("{}applyStyle(_el, {:?});\n", ind, val));
                    }
                    "animation" => {
                        js.push_str(&format!("{}applyAnimation(_el, {:?});\n", ind, val));
                    }
                    "text" | "value" | "label" => {
                        js.push_str(&format!("{}_el.textContent = {:?};\n", ind, val));
                    }
                    "class" | "id" => {
                        js.push_str(&format!("{}_el.setAttribute({:?}, {:?});\n", ind, attr.name, val));
                    }
                    _ => {
                        js.push_str(&format!("{}_el.setAttribute({:?}, {:?});\n", ind, attr.name, val));
                    }
                }
            }
            AttrValue::Expr(expr) => {
                match attr.name.as_str() {
                    "bind" => {
                        // Two-way binding via reactivity system
                        js.push_str(&format!("{}Binding.twoWay(_el, state, {:?}, 'input');\n", ind, expr));
                    }
                    "text" | "value" => {
                        // One-way binding with reactivity
                        js.push_str(&format!("{}Binding.oneWay(_el, 'textContent', state, {:?});\n", ind, expr));
                    }
                    "tpl" => {
                        js.push_str(&format!("{}applyStyle(_el, state.get({:?}));\n", ind, expr));
                    }
                    "animation" => {
                        js.push_str(&format!("{}applyAnimation(_el, state.get({:?}));\n", ind, expr));
                    }
                    "checked" => {
                        js.push_str(&format!("{}Binding.oneWay(_el, 'checked', state, {:?});\n", ind, expr));
                    }
                    "disabled" => {
                        js.push_str(&format!("{}Binding.oneWay(_el, 'disabled', state, {:?});\n", ind, expr));
                    }
                    // Event attributes — skip setAttribute, handled by gen_events
                    "click" | "change" | "input" | "mouse_enter" | "mouse_leave"
                    | "focus" | "blur" | "keydown" | "keyup" | "submit" | "scroll"
                    | "dblclick" | "context_menu" | "mouse_down" | "mouse_up"
                    | "mouse_move" | "touch_start" | "touch_end" | "touch_move" => {}
                    _ => {
                        js.push_str(&format!("{}_el.setAttribute({:?}, state.get({:?}));\n", ind, attr.name, expr));
                    }
                }
            }
            AttrValue::Flag => {
                js.push_str(&format!("{}_el.setAttribute({:?}, '');\n", ind, attr.name));
            }
        }
    }
}

fn gen_events(attrs: &[KyxAttr], js: &mut String, indent: usize) {
    let ind = " ".repeat(indent + 2);
    for attr in attrs {
        let event_name = match attr.name.as_str() {
            "click" => "click",
            "change" => "change",
            "input" => "input",
            "mouse_enter" => "mouseenter",
            "mouse_leave" => "mouseleave",
            "focus" => "focus",
            "blur" => "blur",
            "keydown" => "keydown",
            "keyup" => "keyup",
            "submit" => "submit",
            "scroll" => "scroll",
            "dblclick" => "dblclick",
            "context_menu" => "contextmenu",
            "mouse_down" => "mousedown",
            "mouse_up" => "mouseup",
            "mouse_move" => "mousemove",
            "touch_start" => "touchstart",
            "touch_end" => "touchend",
            "touch_move" => "touchmove",
            _ => continue,
        };
        if let AttrValue::Expr(handler) = &attr.value {
            // Pass the DOM event wrapped as a Kyle event object
            js.push_str(&format!("{}_el.addEventListener({:?}, (e) => {{ {}(createKyleEvent(e)); }});\n", ind, event_name, handler));
        }
    }
}

fn js_tag(tag: &str) -> &str {
    match tag.to_lowercase().as_str() {
        "view" | "column" | "row" | "stack" | "container" => "div",
        "text" | "label" => "span",
        "button" | "iconbutton" => "button",
        "textfield" => "input",
        "passwordfield" => "input",
        "textarea" => "textarea",
        "checkbox" => "input",
        "radio" => "input",
        "image" | "icon" => "img",
        "link" => "a",
        "list" => "ul",
        "form" => "form",
        "dialog" => "dialog",
        "canvas" => "canvas",
        "video" => "video",
        "audio" => "audio",
        "select" => "select",
        "slider" => "input",
        "switch" => "input",
        "progress" => "progress",
        "spinner" => "div",
        _ => "div",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser;

    #[test]
    fn test_generate_simple() {
        let source = r#"<text value="Hello" />"#;
        let file = parser::parse(source).unwrap();
        let js = generate(&file);
        assert!(js.contains("createElement"));
        assert!(js.contains("Hello"));
    }

    #[test]
    fn test_generate_with_events() {
        let source = r#"<button text="Click" click=@handle_click />"#;
        let file = parser::parse(source).unwrap();
        let js = generate(&file);
        assert!(js.contains("addEventListener"));
        assert!(js.contains("createKyleEvent"));
    }

    #[test]
    fn test_generate_with_binding() {
        let source = r#"<text_field bind=@email />"#;
        let file = parser::parse(source).unwrap();
        let js = generate(&file);
        assert!(js.contains("Binding.twoWay"));
    }
}
